{{- if and .Values.ui.networkPolicy.enabled .Values.ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cruise-control.fullname" . }}-ui
  labels:
    {{- include "cruise-control.ui.labels" . | nindent 4 }}
spec:
  {{- if and (not .Values.ui.networkPolicy.policyTypes) (not .Values.ui.networkPolicy.ingress) (not .Values.ui.networkPolicy.egress) }}
  podSelector: {}
  {{- else }}
  podSelector:
    matchLabels:
      {{- include "cruise-control.ui.selectorLabels" . | nindent 6 }}
  {{- end }}

  {{- if .Values.ui.networkPolicy.policyTypes }}
  {{- with .Values.ui.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  policyTypes:
    - Ingress
    - Egress
  {{- end }}

  {{- if .Values.ui.networkPolicy.ingress }}
  {{- with .Values.ui.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  ingress:
  - {}
  {{- end }}

  {{- if .Values.ui.networkPolicy.egress }}
  {{- with .Values.ui.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  egress:
  - {}
  {{- end }}
{{- end }}
