{{- if and .Values.ui.podDisruptionBudget.enabled .Values.ui.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cruise-control.fullname" . }}-ui
  labels:
    {{- include "cruise-control.ui.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cruise-control.ui.selectorLabels" . | nindent 6 }}
  {{- if .Values.ui.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.ui.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.ui.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.ui.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
