{{- if and .Values.ui.serviceAccount.create .Values.ui.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cruise-control.fullname" . }}-ui
  labels:
    {{- include "cruise-control.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ui.serviceAccount.automount | default false }}
{{- end }}
