apiVersion: v2
name: cruise-control
description: A Helm chart to deploy Cruise Control for Apache Kafka
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/linkedin/cruise-control
version: 1.0.9
appVersion: jdk17-cc3.0.3-iam2.3.5
home: https://github.com/devops-ia/helm-cruise-control
keywords:
  - cruise-control
  - apache-kafka
