{{- if .Values.networkPolicy.enabled }}
{{- range $clusterName, $clusterConfig := .Values.clusters }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cruise-control.cluster.fullname" (dict "clusterName" $clusterName "root" $) }}
  labels:
    {{- include "cruise-control.cluster.labels" (dict "clusterName" $clusterName "root" $) | nindent 4 }}
spec:
  {{- if and (not $.Values.networkPolicy.policyTypes) (not $.Values.networkPolicy.ingress) (not $.Values.networkPolicy.egress) }}
  podSelector: {}
  {{- else }}
  podSelector:
    matchLabels:
      {{- include "cruise-control.cluster.selectorLabels" (dict "clusterName" $clusterName "root" $) | nindent 6 }}
  {{- end }}

  {{- if $.Values.networkPolicy.policyTypes }}
  {{- with $.Values.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  policyTypes:
    - Ingress
    - Egress
  {{- end }}

  {{- if $.Values.networkPolicy.ingress }}
  {{- with $.Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  ingress:
  - {}
  {{- end }}

  {{- if $.Values.networkPolicy.egress }}
  {{- with $.Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  egress:
  - {}
  {{- end }}
{{- end }}
{{- end }}
