{{- if .Values.podDisruptionBudget.enabled }}
{{- range $clusterName, $clusterConfig := .Values.clusters }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cruise-control.cluster.fullname" (dict "clusterName" $clusterName "root" $) }}
  labels:
    {{- include "cruise-control.cluster.labels" (dict "clusterName" $clusterName "root" $) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cruise-control.cluster.selectorLabels" (dict "clusterName" $clusterName "root" $) | nindent 6 }}
  {{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $.Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
